import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SearchBar from '@/components/SearchBar'
import FolderList from '@/components/Folder/FolderList'
import FileList from '@/components/File/FileList'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cloud File Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='p-5'>
        <SearchBar></SearchBar>
        <FolderList></FolderList>
        <FileList></FileList>
        </div>


      </main>
    </>
  )
}
